name: 'Depcheck Checker'
description: 'Run depcheck to find unused/missing deps in your code.'
author: "Amol Kapoor <amoljayakapoor@gmail.com>"

branding:
  icon: 'check-circle'
  color: 'green'

runs:
  using: 'docker'
  image: 'Dockerfile'
